version: '3.7'
services:
  postgres:
    image: postgres:13
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=raw
    container_name: "postgres"
    healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
            timeout: 20s
            retries: 10

